# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: git@github.com:deeplex/copier-cpp-library.git
buildver: 0.0.0.1
email: henrik@gassmann.onl
full_name: Henrik Steffen Gaßmann
header_only: true
namespace: cncr
project_name: concrete
project_slug: concrete
semver: 0.0.0-alpha.2
year: '2022'

